# base image
FROM node:alpine



# set working directory
WORKDIR /app


# install and cache app dependencies
COPY ./package.json ./
COPY ./package-lock.json ./

COPY . .

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install 

# start app
CMD ["npm", "start"]

