# base image
FROM node:alpine

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install 

COPY . .

ENV PATH /app/node_modules/.bin:$PATH


# start app
CMD ["npm", "start"]

