version: "2.1"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: ./client
        WORKING_DIR: /src/client
    environment:
      REACT_APP_ENV: development
      BACKEND: api:5000
      NODE_PATH: /src/client/src
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/src
    ports:
      - "3000:3000"
  api:
    command: ["npm", "start"]
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=development
